- ros_topic_name: "/robot_02/b1_joint/controller"
  gz_topic_name: "/model/robot_02/joint/robot_02/b1_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/robot_02/b2_joint/controller"
  gz_topic_name: "/model/robot_02/joint/robot_02/b2_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/robot_02/b3_joint/controller"
  gz_topic_name: "/model/robot_02/joint/robot_02/b3_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/robot_02/p1_joint/controller"
  gz_topic_name: "/model/robot_02/joint/robot_02/p1_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/robot_02/p2_joint/controller"
  gz_topic_name: "/model/robot_02/joint/robot_02/p2_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/robot_02/m1_joint/controller"
  gz_topic_name: "/model/robot_02/joint/robot_02/m1_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/robot_02/m2_joint/controller"
  gz_topic_name: "/model/robot_02/joint/robot_02/m2_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/robot_02/m3_joint/controller"
  gz_topic_name: "/model/robot_02/joint/robot_02/m3_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/robot_02/m4_joint/controller"
  gz_topic_name: "/model/robot_02/joint/robot_02/m4_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/world_cam/model/robot_02/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# - ros_topic_name: "/tf"
#   gz_topic_name: "/model/robot_02/pose"
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   gz_type_name: "gz.msgs.Pose_V"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/tf_static"
#   gz_topic_name: "/model/robot_02/pose_static"
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   gz_type_name: "gz.msgs.Pose_V"
#   direction: GZ_TO_ROS

- ros_topic_name: "/robot_02/cube_11/attach"
  gz_topic_name: "/R02C11/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: ROS_TO_GZ

- ros_topic_name: "/robot_02/cube_11/detach"
  gz_topic_name: "/R02C11/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: ROS_TO_GZ

- ros_topic_name: "/robot_02/cube_12/attach"
  gz_topic_name: "/R02C12/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: ROS_TO_GZ

- ros_topic_name: "/robot_02/cube_12/detach"
  gz_topic_name: "/R02C12/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: ROS_TO_GZ

- ros_topic_name: "/robot_02/cube_21/attach"
  gz_topic_name: "/R02C21/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: ROS_TO_GZ

- ros_topic_name: "/robot_02/cube_21/detach"
  gz_topic_name: "/R02C21/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: ROS_TO_GZ