%YAML:1.0
---
calibration_time: "Thu 03 Nov 2022 01:09:07 PM CST"
image_width: 1280
image_height: 720
flags: 0
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 762.7249337622711, 0., 640.5, 0.,
       762.7249337622711, 360.5, 0., 0., 1. ]
distortion_coefficients: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 0, 0,
       0, 0,
       0 ]
avg_reprojection_error: 1.9313805881497359e+01
