/**:
    ros__parameters:
      video_device: "/dev/video2"
      framerate: 120.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "yuyv"
      #pixel_format: "mjpeg"
      color_format: "yuv422p"
      image_width: 1280
      image_height: 720
      camera_name: "test_camera"
      camera_info_url: "package://img_proc_pkg/config/camera_info.yaml"
